
-<!DOCTYPE html >
-<html>
-<head>
  -<link rel="stylesheet" type="text/css" href="src/css/theme.css" />
  -<script type="application/javascript" src="src/js/canvas.js"></script>
  -</head>
-<body>
-
-<h1>Canvas!</h1>
-<canvas id="canvas">
  -
  -</canvas>
-
-
-
-
-<form action="upload.php" method="post" enctype="multipart/form-data">
  -	Select image to upload:
  -	<input type="file" name="fileToUpload" id="fileToUpload">
  -	<input type="submit" value="Upload Image" name="submit">
  -</form>
-</body>
-<footer>
  -
  -</footer>
-</html> 